include ./cyberdream.conf
# vim:fileencoding=utf-8:foldmethod=marker

map ctrl+equal    change_font_size all +1.0
map ctrl+minus    change_font_size all -1.0

shell_integration disabled

font_family Iosevka
font_size 18.0

enable_audio_bell no
