include ./gruber.conf
vim:fileencoding=utf-8:foldmethod=marker

map ctrl+equal    change_font_size all +1.0
map ctrl+minus    change_font_size all -1.0

shell_integration disabled
text_composition_strategy legacy

enable_audio_bell no
background #202020
# background #000000
# background_opacity 0.9
# font_family JetBrainsMono Nerd Font
font_family Iosevka
background_blur 8
# hide_window_decorations yes

font_size 18

cursor_beam_thickness 3.5
cursor_underline_thickness 2.0
# cursor #ffdd33
cursor #ffffff
macos_thicken_font 0.5

mouse_hide_wait -1.0

visual_bell_duration 0.0
}


# # BEGIN_KITTY_THEME
# # Gruvbox Material Dark Medium
# include current-theme.conf
# # END_KITTY_THEME


# # BEGIN_KITTY_FONTS
# font_family      family="JetBrainsMonoNL Nerd Font Mono"
# bold_font        auto
# italic_font      auto
# bold_italic_font auto
# # END_KITTY_FONTS
